# Generated by Django 5.2.11 on 2026-02-11 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuerequest",
            name="issued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
