"""Service layer for requests domain operations."""

from .export import HEADERS, append_issue_to_xlsx, sync_xlsx_to_gdrive
from .issues import (
    create_issue_request,
    issue_csv_rows,
    issue_detail_context,
    issue_detail_queryset,
    issue_ordered_queryset,
    validate_issue_request_items,
)
from .material_requests import (
    approve_material_request,
    can_approve_material_request,
    can_edit_material_request,
    can_fulfill_material_request,
    can_submit_material_request,
    can_view_material_request,
    chief_pending_material_requests_for_user,
    ensure_can_approve_material_request,
    ensure_can_delete_material_request,
    ensure_can_fulfill_material_request,
    ensure_can_submit_material_request,
    material_request_base_queryset,
    material_request_detail_queryset,
    material_request_form_context,
    material_requests_accessible_for_approval,
    material_requests_accessible_for_fulfillment,
    material_requests_approved_queue_for_user,
    material_requests_pending_approval_for_user,
    material_requests_visible_to_user,
    chief_material_request_history_for_user,
    create_material_request_draft,
    fulfill_material_request,
    normalize_warehouse_requester_fields,
    reject_material_request,
    request_notifications_for_user,
    requester_identity_for_creation,
    should_auto_approve_request,
    submit_material_request,
    update_material_request_draft,
    warehouse_material_request_history,
    warehouse_approved_material_requests_for_user,
    validate_material_request_items,
    validate_requested_items_against_stock,
)
from .search import search_materials
from .stock import StockValidationError, consume_stock_for_issue

__all__ = [
    "HEADERS",
    "append_issue_to_xlsx",
    "create_issue_request",
    "issue_csv_rows",
    "issue_detail_context",
    "issue_detail_queryset",
    "issue_ordered_queryset",
    "sync_xlsx_to_gdrive",
    "approve_material_request",
    "can_approve_material_request",
    "can_edit_material_request",
    "can_fulfill_material_request",
    "can_submit_material_request",
    "can_view_material_request",
    "chief_pending_material_requests_for_user",
    "ensure_can_approve_material_request",
    "ensure_can_delete_material_request",
    "ensure_can_fulfill_material_request",
    "ensure_can_submit_material_request",
    "material_request_base_queryset",
    "material_request_detail_queryset",
    "material_request_form_context",
    "material_requests_accessible_for_approval",
    "material_requests_accessible_for_fulfillment",
    "material_requests_approved_queue_for_user",
    "material_requests_pending_approval_for_user",
    "material_requests_visible_to_user",
    "chief_material_request_history_for_user",
    "create_material_request_draft",
    "fulfill_material_request",
    "normalize_warehouse_requester_fields",
    "request_notifications_for_user",
    "reject_material_request",
    "requester_identity_for_creation",
    "search_materials",
    "should_auto_approve_request",
    "StockValidationError",
    "submit_material_request",
    "consume_stock_for_issue",
    "update_material_request_draft",
    "warehouse_material_request_history",
    "warehouse_approved_material_requests_for_user",
    "validate_issue_request_items",
    "validate_material_request_items",
    "validate_requested_items_against_stock",
]
